/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class starknet_crypto_CryptoCpp */

#ifndef _Included_starknet_crypto_CryptoCpp
#define _Included_starknet_crypto_CryptoCpp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     starknet_crypto_CryptoCpp
 * Method:    pedersen
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_starknet_crypto_CryptoCpp_pedersen
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     starknet_crypto_CryptoCpp
 * Method:    getPublicKey
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_starknet_crypto_CryptoCpp_getPublicKey
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     starknet_crypto_CryptoCpp
 * Method:    verify
 * Signature: ([B[B[B[B)z
 */
JNIEXPORT jboolean JNICALL Java_starknet_crypto_CryptoCpp_verify
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     starknet_crypto_CryptoCpp
 * Method:    sign
 * Signature: ([B[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_starknet_crypto_CryptoCpp_sign
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
