name: Bug Report
description: File a bug report
labels: [ "bug" ]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened
      description: Describe the issue here.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Stack trace
      description: Please provide stack trace output of the error
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Please provide the steps required to reproduce the issue
      value: 1.
    validations:
      required: true

  - type: input
    id: sdk-version
    attributes:
      label: SDK Version
      description: What SDK version are you using?
    validations:
      required: true

  - type: dropdown
    id: language
    attributes:
      label: Language
      description: What language are you using?
      options:
        - Java
        - Kotlin
        - Scala
        - Other
    validations:
      required: true

  - type: input
    id: other-language
    attributes:
      label: Language
      description: If you selected `Other` in previous question, please specify here
      value: n/a
    validations:
      required: false

  - type: input
    id: language-version
    attributes:
      label: Language version
      description: What version of the language selected are you using?
    validations:
      required: true

  - type: dropdown
    id: operating-systems
    attributes:
      label: What type of Operating System are you seeing the problem on?
      multiple: true
      options:
        - Linux
        - Windows
        - Mac
    validations:
      required: true

  - type: checkboxes
    id: verified-not-exists
    attributes:
      label: Confirmation
      options:
        - label: I have verified that an issue for this problem does not already exist

# Thanks to https://github.com/MarketingPipeline/Awesome-Repo-Template
