name: Bug Report
description: File a bug report
labels: [ "bug" ]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the issue here.
    validations:
      required: true
  - type: dropdown
    id: language
    attributes:
      label: What language are you using?
      options:
        - Java
        - Kotlin
        - Scala
        - Other
    validations:
      required: true

  - type: input
    id: other-language
    attributes:
      label: Language
      description: If you selected `Other` in previous question, please specify here
    validations:
      required: false

  - type: input
    id: language-version
    attributes:
      label: Language version
      description: Please specify the version of the language you are using
    validations:
      required: true

  - type: dropdown
    id: operating-systems
    attributes:
      label: What type of Operating System are you seeing the problem on?
      multiple: true
      options:
        - Linux
        - Windows
        - Mac
    validations:
      required: true

# Thanks to https://github.com/MarketingPipeline/Awesome-Repo-Template
