/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_swmansion_starknet_crypto_StarknetCurve */

#ifndef _Included_com_swmansion_starknet_crypto_StarknetCurve
#define _Included_com_swmansion_starknet_crypto_StarknetCurve
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_swmansion_starknet_crypto_StarknetCurve
 * Method:    pedersen
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_swmansion_starknet_crypto_StarknetCurve_pedersen
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     com_swmansion_starknet_crypto_StarknetCurve
 * Method:    getPublicKey
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_swmansion_starknet_crypto_StarknetCurve_getPublicKey
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_swmansion_starknet_crypto_StarknetCurve
 * Method:    verify
 * Signature: ([B[B[B[B)z
 */
JNIEXPORT jboolean JNICALL Java_com_swmansion_starknet_crypto_StarknetCurve_verify
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     com_swmansion_starknet_crypto_StarknetCurve
 * Method:    sign
 * Signature: ([B[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_swmansion_starknet_crypto_StarknetCurve_sign
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
